name: ESLint

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  test:
    name: Lint
    runs-on: ubuntu-latest
    container:
      image: node:18.0.0

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Ignore Husky
        run: npm set-script prepare ""

      - name: npm install
        run: npm install

      - name: npm cache verify
        run: npm cache verify

      - name: npm eslint
        run: npm run lint